name: DevDeploy

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  push:
    branches: [ "master" ]
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  DevDeploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up ssh-agent
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        script_stop: true
        script: |
          cd manga-bot/tg-manga-bot-dev
          git pull origin master
          docker container rm -f manga-bot-dev 2> /dev/null || true
          docker build . -t manga-bot-dev
          docker run --name manga-bot-dev --restart=always -dti \
          --env BOT_TOKEN=${{ 6096620656:AAF1co5Hs7gjvJ9r55MBKyQ8L1DUmcauxHE }} \
          --env API_ID=${{ 3847632 }} \
          --env API_HASH=${{ 1a9708f807ddd06b10337f2091c67657 }} \
          --env DATABASE_URL_PRIMARY=${{ secrets.DEV_DATABASE_URI }} \
          manga-bot-dev 
